import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import { doc, getDoc, getFirestore, serverTimestamp, writeBatch } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js";

const app = initializeApp({apiKey:"AIzaSyD19Zoc4lOgeZY5SBHf9zQpZPdk4GV6O5o",authDomain:"it-serwis-opole-lukdobo70.firebaseapp.com",projectId:"it-serwis-opole-lukdobo70",storageBucket:"it-serwis-opole-lukdobo70.firebasestorage.app",messagingSenderId:"40030709547",appId:"1:40030709547:web:e39143edbeac832014876e"});
const db = getFirestore(app);
const form = document.querySelector('#shipping-form');
const steps = [...document.querySelectorAll('.wizard-step')];
const navItems = [...document.querySelectorAll('[data-step-nav]')];
const photosInput = document.querySelector('#device-photos');
const previews = document.querySelector('#photo-previews');
let currentStep = 1;
let preparedPhotos = [];

function showStep(number){currentStep=number;steps.forEach(s=>s.classList.toggle('active',+s.dataset.step===number));navItems.forEach(n=>{const v=+n.dataset.stepNav;n.classList.toggle('active',v===number);n.classList.toggle('done',v<number)});window.scrollTo({top:document.querySelector('.wizard-shell').offsetTop-95,behavior:'smooth'})}
function validateStep(number){const required=[...steps[number-1].querySelectorAll('[required]')];for(const field of required){if(!field.checkValidity()){field.reportValidity();return false}}return true}
document.querySelectorAll('.wizard-next').forEach(button=>button.addEventListener('click',()=>{if(currentStep===3){const boxes=[...steps[2].querySelectorAll('input[type="checkbox"]')];if(!boxes.every(x=>x.checked)){alert('Zaznacz wszystkie punkty instrukcji pakowania.');return}}if(validateStep(currentStep))showStep(currentStep+1)}));
document.querySelectorAll('.wizard-back').forEach(button=>button.addEventListener('click',()=>showStep(currentStep-1)));

function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);let quality=.72;let data=canvas.toDataURL('image/jpeg',quality);while(data.length>380000&&quality>.4){quality-=.08;data=canvas.toDataURL('image/jpeg',quality)}resolve({name:file.name.replace(/\.[^.]+$/,'.jpg'),size:data.length,dataUrl:data})};image.src=reader.result};reader.readAsDataURL(file)})}

photosInput.addEventListener('change',async()=>{const files=[...photosInput.files].slice(0,3);previews.innerHTML='<p class="photo-processing">Przygotowujemy zdjęcia…</p>';try{preparedPhotos=await Promise.all(files.map(compressImage));previews.innerHTML=preparedPhotos.map((photo,index)=>`<figure><img src="${photo.dataUrl}" alt="Podgląd zdjęcia ${index+1}"><figcaption>${photo.name}</figcaption></figure>`).join('')}catch{preparedPhotos=[];previews.innerHTML='<p class="photo-error">Nie udało się odczytać zdjęć. Wybierz inne pliki.</p>'}});

function createCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',bytes=crypto.getRandomValues(new Uint8Array(16));let value='';bytes.forEach(x=>value+=chars[x%chars.length]);return `IT-${value.slice(0,4)}-${value.slice(4,8)}-${value.slice(8,12)}-${value.slice(12,16)}`}

form.addEventListener('submit',async event=>{event.preventDefault();if(!validateStep(4))return;const button=document.querySelector('#create-shipping'),label=button.querySelector('.submit-label'),message=document.querySelector('#shipping-message');button.disabled=true;label.textContent='Zapisywanie…';message.className='form-message';const code=createCode();try{const batch=writeBatch(db);batch.set(doc(db,'wysylki',code),{trackingCode:code,name:form.elements.name.value.trim(),contact:form.elements.contact.value.trim(),device:form.elements.device.value,model:form.elements.model.value.trim(),description:form.elements.description.value.trim(),parcelLocker:form.elements.parcelLocker.value.trim(),returnMethod:form.elements.returnMethod.value,contactTime:form.elements.contactTime.value,photosCount:preparedPhotos.length,status:'Zgłoszenie przyjęte',consent:true,source:'kreator-paczkomat',createdAt:serverTimestamp()});preparedPhotos.forEach((photo,index)=>batch.set(doc(db,'wysylki',code,'zdjecia',String(index+1)),{name:photo.name,size:photo.size,dataUrl:photo.dataUrl,createdAt:serverTimestamp()}));batch.set(doc(db,'statusy',code),{code,device:form.elements.device.value,status:'Zgłoszenie przyjęte',message:'Oczekuje na kontakt serwisu i przekazanie danych Paczkomatu docelowego.',currentStep:1,updatedAt:serverTimestamp()});await batch.commit();document.querySelector('#created-code').textContent=code;document.querySelector('#status-form').elements.trackingCode.value=code;showStep(5)}catch(error){console.error(error);message.classList.add('error');message.textContent='Nie udało się utworzyć zgłoszenia. Spróbuj ponownie lub skontaktuj się przez formularz główny.'}finally{button.disabled=false;label.textContent='Utwórz zgłoszenie'}});

document.querySelector('#copy-code').addEventListener('click',async()=>{const code=document.querySelector('#created-code').textContent;await navigator.clipboard.writeText(code);document.querySelector('#copy-code').textContent='Skopiowano ✓'});

document.querySelector('#status-form').addEventListener('submit',async event=>{event.preventDefault();const code=event.currentTarget.elements.trackingCode.value.trim().toUpperCase(),result=document.querySelector('#status-result');result.className='status-result loading';result.textContent='Sprawdzamy status…';try{const snapshot=await getDoc(doc(db,'statusy',code));if(!snapshot.exists()){result.className='status-result error';result.textContent='Nie znaleziono takiego kodu. Sprawdź zapis i spróbuj ponownie.';return}const data=snapshot.data(),date=data.updatedAt?.toDate?.().toLocaleString('pl-PL')||'przed chwilą';result.className='status-result success';result.innerHTML=`<span>AKTUALNY STATUS</span><strong>${data.status}</strong><p>${data.message}</p><small>${data.device} • aktualizacja: ${date}</small>`}catch{result.className='status-result error';result.textContent='Nie udało się pobrać statusu. Spróbuj ponownie później.'}});

